name = "MixedAnova"
uuid = "72e9ff3b-fbb7-4ec3-b65d-9c3416869820"
authors = ["Jejulia <Jejulia@users.noreply.github.com> and contributors"]
version = "0.3.3-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"

[compat]
DataFrames = "1"
Distributions = "0.23, 0.24, 0.25"
FixedEffectModels = "1.3"
GLM = "1.5"
HypothesisTests = "0.10"
MixedModels = "3.1.3, 4"
Reexport = "0.2, 1.0"
StatsBase = "0.33"
StatsModels = "0.6"
Tables = "1.0"
julia = "1.5"

[targets]
test = ["Test", "CSV", "RDatasets"]
